services:
    lexonomy:
        image: ${ORG:-elexis-eu}/lexonomy:${VER:-dev}
        build:
            context: .
            args:
                VER: ${VER:-dev}
        volumes:
            - ./website/siteconfig.json.template:/opt/service/website/siteconfig.json
            - ./website/config.js.template:/opt/service/website/config.js
            - ./data:/opt/service/data
        ports:
            - "8000:8000"
            - "5678:5678"  # Debug port

