services:
    lexonomy:
        image: ${ORG:-elexis-eu/lexonomy}:${VER:-latest}
        build:
            context: .
            args:
                VER: ${VER:-latest}
        volumes:
            - ./website/siteconfig.json.template:/opt/service/website/siteconfig.json
            - ./data:/opt/service/data
        ports:
            - "8000:8000"

